#pragma once

#if RENDER_PERFORMANCE_TIMER

#include "RenderTimeMetrics_def.h"

TimeClockPrecision PerformanceCounter_GetAverage(PerformanceCounter_PTR p_performanceCounter);
void PerformanceCounter_PushSample(PerformanceCounter_PTR p_performanceCounter, TimeClockPrecision p_sampleTime);
void PerformanceCounter_IncrementCounter(PerformanceCounter_PTR p_performanceCounter);
void PerformanceCounter_AddTime(PerformanceCounter_PTR p_performanceCounter, TimeClockPrecision p_sampleTime);
void SolidRendererMetrics_Print(SolidRendererMetrics_PTR p_wireframeRenderPerformance);

#endif