#pragma once

#include "PixelColorCalculation_def.h"
#include "DataStructures/ARRAY.h"
#include "Renderer/Solid/SolidRenderer.h"
#include "Light/Light_def.h"
#include "Raster/Rasterizer.h"

ARRAY_ALLOC_FUNCTION(FlatShadingPixelCalculation, Array_FlatShadingPixelCalculation_PTR, FlatShadingPixelCalculation)
ARRAY_PUSHBACKREALLOC_ENPTY_FUNCTION(FlatShadingPixelCalculation, Array_FlatShadingPixelCalculation_PTR, FlatShadingPixelCalculation)

void PixelColorCaluclation_Polygon_PushCalculations(PolygonPipelineV2_PTR p_polygonPipeline, Vector4f_PTR p_polygonWorldNormal, SolidRenderer_Memory_PTR p_solidRendererMemory);

void FlatShadingPixelCalculation_PreCalculation(FlatShadingPixelCalculation_PTR p_flatShadingPixelCalculation, RenderLights_PTR p_renderLights, SolidRenderer_Memory_PTR p_solidRendererMemory);

void FlatShadingPixelCalculation_ShadePixelColor(
	const FlatShadingPixelCalculation_PTR p_flatShadingPixelCalculation, const PolygonPipelineV2_PTR p_polygonPipeline,
	RenderLights_PTR p_renderLights, Material_PTR p_material,
	const PolygonRasterizerIterator_PTR p_polygonRasterize, Color3f_PTR out_pixelColor);

// void FlatShadingPixelcalculation_PixelColor()