site_name: Software Renderer
theme: 'windmill'
nav:
    - 'Entity editor selection': "entity_editor_selection.md"
    - 'Software Renderer': "software_renderer.md"
extra_javascript:
    - ./js/custom.js
extra_css:
    - ./css/custom.css