#pragma once

#include "v2/_interface/VectorC_def.h"

typedef struct SEGMENT_VECTOR2F_TYP
{
	VECTOR2F Begin;
	VECTOR2F End;
} SEGMENT_VECTOR2F, * SEGMENT_VECTOR2F_PTR;

typedef struct SEGMENT_VECTOR3F_TYP
{
	VECTOR3F Begin;
	VECTOR3F End;
} SEGMENT_VECTOR3F, * SEGMENT_VECTOR3F_PTR;

typedef struct SEGMENT_VECTOR4F_TYP
{
	VECTOR4F Begin;
	VECTOR4F End;
} SEGMENT_VECTOR4F, * SEGMENT_VECTOR4F_PTR;

