#pragma once

#include "Vertex_def.h"
#include "DataStructures/ARRAY_def.h"
#include "Objects/Resource/Polygon_def.h"

typedef size_t VertexIndex;

typedef struct POLYGON_VERTEXINDEX_TYP
{
	POLYGON_TYPE_DEFINITION(VertexIndex)
} POLYGON_VERTEXINDEX, * POLYGON_VERTEXINDEX_PTR;

typedef struct ARRAY_POLYGON_VERTEXINDEX_TYP
{
	ARRAY_TYPE_DEFINITION(POLYGON_VERTEXINDEX)
}ARRAY_POLYGON_VERTEXINDEX, * ARRAY_POLYGON_VERTEXINDEX_PTR;

typedef struct MESH_TYP
{
	ARRAY_VERTEX Vertices;
	ARRAY_POLYGON_VERTEXINDEX Polygons;
}MESH, *MESH_PTR;

typedef size_t MESHRESOURCE_KEY;

typedef struct MESHRESOURCE_TYP
{
	MESHRESOURCE_KEY Key;
	MESH Mesh;
	size_t UsageCount;
}MESHRESOURCE, * MESHRESOURCE_HANDLE;

typedef struct MESHRESOURCE_PROVIDER_TYP
{
	ARRAY_TYPE_DEFINITION(MESHRESOURCE_HANDLE)
}MESHRESOURCE_PROVIDER, * MESHRESOURCE_PROVIDER_PTR;